version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: yfl-postgres
    restart: unless-stopped
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    env_file:
      - .env
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - yfl-network

volumes:
  postgres_data:

networks:
  yfl-network:
    driver: bridge
